// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type League struct {
	ID          int32 `json:"id"`
	LeagueId    int32 `json:"leagueId"`
	Year        int32 `json:"year"`
	TeamCount   int32 `json:"teamCount"`
	CurrentWeek int32 `json:"currentWeek"`
	NflWeek     int32 `json:"nflWeek"`
}

type Team struct {
	ID                     int32          `json:"id"`
	LeagueID               int32          `json:"league_id"`
	TeamId                 int32          `json:"teamId"`
	Year                   int32          `json:"year"`
	TeamAbbrv              string         `json:"teamAbbrv"`
	TeamName               string         `json:"teamName"`
	Owners                 sql.NullString `json:"owners"`
	DivisionId             sql.NullString `json:"divisionId"`
	DivisionName           sql.NullString `json:"divisionName"`
	Wins                   sql.NullInt32  `json:"wins"`
	Losses                 sql.NullInt32  `json:"losses"`
	Ties                   sql.NullInt32  `json:"ties"`
	PointsFor              sql.NullInt32  `json:"pointsFor"`
	PointsAgainst          sql.NullInt32  `json:"pointsAgainst"`
	WaiverRank             sql.NullInt32  `json:"waiverRank"`
	Acquisitions           sql.NullInt32  `json:"acquisitions"`
	AcquisitionBudgetSpent sql.NullInt32  `json:"acquisitionBudgetSpent"`
	Drops                  sql.NullInt32  `json:"drops"`
	Trades                 sql.NullInt32  `json:"trades"`
	StreakType             sql.NullString `json:"streakType"`
	StreakLength           sql.NullInt32  `json:"streakLength"`
	Standing               sql.NullInt32  `json:"standing"`
	FinalStanding          sql.NullInt32  `json:"finalStanding"`
	DraftProjRank          sql.NullInt32  `json:"draftProjRank"`
	PlayoffPct             sql.NullInt32  `json:"playoffPct"`
	LogoUrl                sql.NullString `json:"logoUrl"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID int64     `json:"user_id"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type User struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	Name       string         `json:"name"`
	Email      sql.NullString `json:"email"`
	Activated  bool           `json:"activated"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
	Version    int32          `json:"version"`
}
