// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type League struct {
	ID          int32         `json:"id"`
	LeagueId    int32         `json:"leagueId"`
	Year        int32         `json:"year"`
	TeamCount   sql.NullInt32 `json:"teamCount"`
	CurrentWeek sql.NullInt32 `json:"currentWeek"`
	NflWeek     sql.NullInt32 `json:"nflWeek"`
}
