// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type League struct {
	ID          int32 `json:"id"`
	LeagueId    int32 `json:"leagueId"`
	Year        int32 `json:"year"`
	TeamCount   int32 `json:"teamCount"`
	CurrentWeek int32 `json:"currentWeek"`
	NflWeek     int32 `json:"nflWeek"`
}
